// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package io.github.s3s3l.yggdrasil.rpc.grpc.test.hello;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_People_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_People_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Hello.proto\022\005hello\"/\n\006People\022\022\n\nfirst_" +
      "name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\"&\n\007Message" +
      "\022\014\n\004from\030\001 \001(\t\022\r\n\005words\030\002 \001(\t24\n\005Hello\022+" +
      "\n\010SayHello\022\r.hello.People\032\016.hello.Messag" +
      "e\"\000BC\n-io.github.s3s3l.yggdrasil.rpc.grp" +
      "c.test.helloB\nHelloProtoP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hello_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_People_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_hello_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hello_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_Message_descriptor,
        new java.lang.String[] { "From", "Words", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
