// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package io.github.s3s3l.yggdrasil.rpc.grpc.test.hello;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string words = 2;</code>
   * @return The words.
   */
  java.lang.String getWords();
  /**
   * <code>string words = 2;</code>
   * @return The bytes for words.
   */
  com.google.protobuf.ByteString
      getWordsBytes();
}
