// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package io.github.s3s3l.yggdrasil.rpc.grpc.test.hello;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
