receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  elasticsearch/trace:
    endpoints: [https://es01:9200]
    user: elastic
    api_key: dkkydFJKTUJwX2lhNXdlY3pUNkU6RGVVT1Bqb0VUbnV2NldkTHkybW9HUQ==
    traces_index: otel_trace_index
    tls:
      insecure_skip_verify: true
  elasticsearch/log:
    endpoints: [https://es01:9200]
    user: elastic
    api_key: dkkydFJKTUJwX2lhNXdlY3pUNkU6RGVVT1Bqb0VUbnV2NldkTHkybW9HUQ==
    logs_index: otel_log_index
    tls:
      insecure_skip_verify: true
  elasticsearch/metric:
    endpoints: [https://es01:9200]
    user: elastic
    api_key: dkkydFJKTUJwX2lhNXdlY3pUNkU6RGVVT1Bqb0VUbnV2NldkTHkybW9HUQ==
    index: otel_metric_index
    tls:
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elasticsearch/trace]
    metrics:
      receivers: [otlp]
      exporters: [elasticsearch/metric]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch/log]
