// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteGuide.proto

package io.github.s3s3l.yggdrasil.rpc.grpc.test.routeguide;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  java.util.List<io.github.s3s3l.yggdrasil.rpc.grpc.test.routeguide.Feature> 
      getFeatureList();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  io.github.s3s3l.yggdrasil.rpc.grpc.test.routeguide.Feature getFeature(int index);
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  java.util.List<? extends io.github.s3s3l.yggdrasil.rpc.grpc.test.routeguide.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  io.github.s3s3l.yggdrasil.rpc.grpc.test.routeguide.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
