// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Yrpc.proto

package io.github.s3s3l.yggdrasil.rpc.grpc.yrpc;

/**
 * Protobuf type {@code yrpc.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yrpc.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    serializeType_ = "";
    service_ = "";
    argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    args_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.YrpcProto.internal_static_yrpc_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.YrpcProto.internal_static_yrpc_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.class, io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.Builder.class);
  }

  public static final int SERIALIZETYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object serializeType_;
  /**
   * <code>string serializeType = 1;</code>
   * @return The serializeType.
   */
  @java.lang.Override
  public java.lang.String getSerializeType() {
    java.lang.Object ref = serializeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serializeType_ = s;
      return s;
    }
  }
  /**
   * <code>string serializeType = 1;</code>
   * @return The bytes for serializeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSerializeTypeBytes() {
    java.lang.Object ref = serializeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serializeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_FIELD_NUMBER = 2;
  private volatile java.lang.Object service_;
  /**
   * <code>string service = 2;</code>
   * @return The service.
   */
  @java.lang.Override
  public java.lang.String getService() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      service_ = s;
      return s;
    }
  }
  /**
   * <code>string service = 2;</code>
   * @return The bytes for service.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceBytes() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      service_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARGTYPES_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList argTypes_;
  /**
   * <code>repeated string argTypes = 3;</code>
   * @return A list containing the argTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getArgTypesList() {
    return argTypes_;
  }
  /**
   * <code>repeated string argTypes = 3;</code>
   * @return The count of argTypes.
   */
  public int getArgTypesCount() {
    return argTypes_.size();
  }
  /**
   * <code>repeated string argTypes = 3;</code>
   * @param index The index of the element to return.
   * @return The argTypes at the given index.
   */
  public java.lang.String getArgTypes(int index) {
    return argTypes_.get(index);
  }
  /**
   * <code>repeated string argTypes = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the argTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getArgTypesBytes(int index) {
    return argTypes_.getByteString(index);
  }

  public static final int ARGS_FIELD_NUMBER = 4;
  private java.util.List<com.google.protobuf.ByteString> args_;
  /**
   * <code>repeated bytes args = 4;</code>
   * @return A list containing the args.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getArgsList() {
    return args_;
  }
  /**
   * <code>repeated bytes args = 4;</code>
   * @return The count of args.
   */
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <code>repeated bytes args = 4;</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  public com.google.protobuf.ByteString getArgs(int index) {
    return args_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serializeType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serializeType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, service_);
    }
    for (int i = 0; i < argTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, argTypes_.getRaw(i));
    }
    for (int i = 0; i < args_.size(); i++) {
      output.writeBytes(4, args_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serializeType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serializeType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, service_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < argTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(argTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getArgTypesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < args_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(args_.get(i));
      }
      size += dataSize;
      size += 1 * getArgsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request)) {
      return super.equals(obj);
    }
    io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request other = (io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request) obj;

    if (!getSerializeType()
        .equals(other.getSerializeType())) return false;
    if (!getService()
        .equals(other.getService())) return false;
    if (!getArgTypesList()
        .equals(other.getArgTypesList())) return false;
    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERIALIZETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSerializeType().hashCode();
    hash = (37 * hash) + SERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getService().hashCode();
    if (getArgTypesCount() > 0) {
      hash = (37 * hash) + ARGTYPES_FIELD_NUMBER;
      hash = (53 * hash) + getArgTypesList().hashCode();
    }
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yrpc.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yrpc.Request)
      io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.YrpcProto.internal_static_yrpc_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.YrpcProto.internal_static_yrpc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.class, io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.Builder.class);
    }

    // Construct using io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serializeType_ = "";

      service_ = "";

      argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      args_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.YrpcProto.internal_static_yrpc_Request_descriptor;
    }

    @java.lang.Override
    public io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request getDefaultInstanceForType() {
      return io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request build() {
      io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request buildPartial() {
      io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request result = new io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request(this);
      int from_bitField0_ = bitField0_;
      result.serializeType_ = serializeType_;
      result.service_ = service_;
      if (((bitField0_ & 0x00000001) != 0)) {
        argTypes_ = argTypes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.argTypes_ = argTypes_;
      if (((bitField0_ & 0x00000002) != 0)) {
        args_ = java.util.Collections.unmodifiableList(args_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.args_ = args_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request) {
        return mergeFrom((io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request other) {
      if (other == io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request.getDefaultInstance()) return this;
      if (!other.getSerializeType().isEmpty()) {
        serializeType_ = other.serializeType_;
        onChanged();
      }
      if (!other.getService().isEmpty()) {
        service_ = other.service_;
        onChanged();
      }
      if (!other.argTypes_.isEmpty()) {
        if (argTypes_.isEmpty()) {
          argTypes_ = other.argTypes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureArgTypesIsMutable();
          argTypes_.addAll(other.argTypes_);
        }
        onChanged();
      }
      if (!other.args_.isEmpty()) {
        if (args_.isEmpty()) {
          args_ = other.args_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureArgsIsMutable();
          args_.addAll(other.args_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serializeType_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              service_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureArgTypesIsMutable();
              argTypes_.add(s);
              break;
            } // case 26
            case 34: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureArgsIsMutable();
              args_.add(v);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object serializeType_ = "";
    /**
     * <code>string serializeType = 1;</code>
     * @return The serializeType.
     */
    public java.lang.String getSerializeType() {
      java.lang.Object ref = serializeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serializeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serializeType = 1;</code>
     * @return The bytes for serializeType.
     */
    public com.google.protobuf.ByteString
        getSerializeTypeBytes() {
      java.lang.Object ref = serializeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serializeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serializeType = 1;</code>
     * @param value The serializeType to set.
     * @return This builder for chaining.
     */
    public Builder setSerializeType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serializeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serializeType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerializeType() {
      
      serializeType_ = getDefaultInstance().getSerializeType();
      onChanged();
      return this;
    }
    /**
     * <code>string serializeType = 1;</code>
     * @param value The bytes for serializeType to set.
     * @return This builder for chaining.
     */
    public Builder setSerializeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serializeType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object service_ = "";
    /**
     * <code>string service = 2;</code>
     * @return The service.
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service = 2;</code>
     * @return The bytes for service.
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service = 2;</code>
     * @param value The service to set.
     * @return This builder for chaining.
     */
    public Builder setService(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      service_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string service = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearService() {
      
      service_ = getDefaultInstance().getService();
      onChanged();
      return this;
    }
    /**
     * <code>string service = 2;</code>
     * @param value The bytes for service to set.
     * @return This builder for chaining.
     */
    public Builder setServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      service_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureArgTypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        argTypes_ = new com.google.protobuf.LazyStringArrayList(argTypes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @return A list containing the argTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getArgTypesList() {
      return argTypes_.getUnmodifiableView();
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @return The count of argTypes.
     */
    public int getArgTypesCount() {
      return argTypes_.size();
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The argTypes at the given index.
     */
    public java.lang.String getArgTypes(int index) {
      return argTypes_.get(index);
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the argTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getArgTypesBytes(int index) {
      return argTypes_.getByteString(index);
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index to set the value at.
     * @param value The argTypes to set.
     * @return This builder for chaining.
     */
    public Builder setArgTypes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgTypesIsMutable();
      argTypes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param value The argTypes to add.
     * @return This builder for chaining.
     */
    public Builder addArgTypes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgTypesIsMutable();
      argTypes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param values The argTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllArgTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureArgTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, argTypes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearArgTypes() {
      argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param value The bytes of the argTypes to add.
     * @return This builder for chaining.
     */
    public Builder addArgTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureArgTypesIsMutable();
      argTypes_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> args_ = java.util.Collections.emptyList();
    private void ensureArgsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        args_ = new java.util.ArrayList<com.google.protobuf.ByteString>(args_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @return A list containing the args.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getArgsList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(args_) : args_;
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public com.google.protobuf.ByteString getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @param index The index to set the value at.
     * @param value The args to set.
     * @return This builder for chaining.
     */
    public Builder setArgs(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
      args_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @param value The args to add.
     * @return This builder for chaining.
     */
    public Builder addArgs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
      args_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @param values The args to add.
     * @return This builder for chaining.
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureArgsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, args_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes args = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearArgs() {
      args_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yrpc.Request)
  }

  // @@protoc_insertion_point(class_scope:yrpc.Request)
  private static final io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request();
  }

  public static io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.s3s3l.yggdrasil.rpc.grpc.yrpc.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

