global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'ba-extends'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs: 
      - targets: ['172.17.0.1:9321']
